### ISSUE TITLE
Wrong username in welcome message

### ISSUE THREAD

**Issue by Sv443** [Crazy-Marvin/FunnyTelegramBot#2]
The "welcome message" that's displayed when starting a chat with the bot shows the username `@Sv443` which isn't mine. I'd recommend changing it or removing the @, so that dude doesn't get spammed or something. My username on Telegram is `@Sv_443`  
  
![grafik](https://user-images.githubusercontent.com/38158426/137591406-0df2a140-d740-42ec-8dd9-8852ec5cdfdb.png)

**Comment by CrazyMarvin** [comment]
Thanks for the info.
Which option do you prefer? Updating the username or removing it?

**Comment by Sv443** [comment]
It doesn't really matter to me, but just to give you an answer, you can change it to `@Sv_443`

**Comment by CrazyMarvin** [comment]
Done 👌
